# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "edidor"
license = "MIT"
licenselink = "https://github.com/sfengyuan/edidor/blob/master/LICENSE"
description = "a hugo theme that looks like editors with infinite color modes"
homepage = "https://github.com/sfengyuan/edidor"
tags = ["blog", "editor", "edidor"]
features = ["personal", "color generator", "infinite color modes"]
min_version = 0.40

[author]
  name = "sunfy"
  homepage = "https://sunfy.xyz/"
